package com.pause.shared

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * A proposal generated by the Local Intelligence Engine to intervene.
 *
 * The keyboard UI renders this non-blockingly. The intervention NEVER
 * blocks typing, requires NO user action, and NEVER displays the user's
 * text content.
 *
 * @param id          Unique identifier for this intervention (for dedup)
 * @param type        Visual treatment to use
 * @param priority    Higher = shown first if multiple are pending
 * @param content     Neutral message text (e.g., "Take a breath") — must NOT
 *                    reference the user's actual typed content
 * @param durationMs  How long the intervention should remain visible
 */
@Parcelize
data class InterventionProposal(
    val id: String,
    val type: InterventionType,
    val priority: Int,
    val content: String,
    val durationMs: Long
) : Parcelable
