org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options="-Xmx2048m"
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

android.useAndroidX=true
android.nonTransitiveR8=true
android.sandbox.sdkDownloadWhenNone=true

# Compose compiler reports
android.compose.compiler Reports=true
kotlinx.coroutines.debug=off
